-- insert into User (username, email, password, active, role) values ('admin', 'admin@gmail.com', '$2a$10$jAEf7ZvYL41BKIC3W.na7./SmPFuB2xsEknOxuvE/QEixox6lsMDC', true, 'ROLE_ADMIN');
--
-- insert into User (username, email, password, active, role) values ('Younten', 'adminYT@gmail.com', '$2y$10$uwslZFS.czXR6VE7XzyBTuH.xGtdDmBBnioj2J/KZqJr0cHDEr3fa', true, 'ROLE_ADMIN');
--
--
--
